import type { Metadata } from "next";
import { Geist, Geist_Mono,Space_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Space_Mono({
  variable: "--font-geist-mono",
  weight: "400",
  subsets: ["latin"],
});


const commitMono = localFont({
  src: './fonts/CommitMono-400-Regular.otf',
  variable: '--font-commit-mono',
})

export const metadata: Metadata = {
  title: "Revolt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${commitMono.variable} font-sans bg-background text-surface-700 dark:text-surface-100 antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
